#pragma once

// CYD Board: ESP32-2432S028R -- Ambient light sensor (LDR)
// GPIO 34 = ADC1_CHANNEL_6

#define CYD_LIGHT_SENSOR_ADC_UNIT ADC_UNIT_1
#define CYD_LIGHT_SENSOR_ADC_CHANNEL ADC_CHANNEL_6
#define CYD_LIGHT_SENSOR_ADC_ATTEN ADC_ATTEN_DB_12
#define CYD_LIGHT_SENSOR_ADC_BITWIDTH ADC_BITWIDTH_DEFAULT
